#!/bin/bash
source $HOME/.dotfiles/shell/functions/bash_git_completion

alias g='git'
alias gs='git status'
alias gc='git commit'
alias gca='git commit -a'
alias ga='git add'
alias gco='git checkout '
alias gb='git branch'
alias gm='git merge'
alias gd="git diff"
alias gg="git grep --color -n"
alias ggi="git grep -ni"
alias gk="gitk 2>/dev/null --all &"

complete -o default -o nospace -F _git_branch gb
complete -o default -o nospace -F _git_checkout gco
