# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source $HOME/.dotfiles/shell/shell_aliases # Shell Aliases
source $HOME/.dotfiles/shell/shell_exports # Shell Exports
#source $HOME/.dotfiles/shell/shell_paths   # Shell Paths

source $HOME/.dotfiles/git/git_aliases # Git Aliases

if [[ -s "$HOME/.zshrc.local" ]]; then
  source $HOME/.zshrc.local # Customizations
fi
