# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export KEYTIMEOUT=1

source $HOME/.dotfiles/shell/shell_exports # Shell Exports

source $HOME/.dotfiles/git/git_aliases # Git Aliases
source $HOME/.dotfiles/shell/shell_aliases # Shell Aliases

if [[ -s "$HOME/.zshrc.local" ]]; then
  source $HOME/.zshrc.local # Customizations
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
