#!/bin/bash

# git

alias g='git'
alias gst='git status'
alias gc='git commit'
alias ga='git add'
alias gco='git checkout'
alias gb='git branch'
alias gm='git merge'
alias gd="git diff --color"
alias gg="git grep --color -n"
alias ggi="git grep -ni"
alias gk="gitk 2>/dev/null --all &"
alias gx="gitx"

alias g="git"
__git_complete g _git

alias gco="git checkout"
__git_complete gco _git_checkout
