#!/bin/bash

install_packages() {
    # List of libraries to install
    local libraries=(
        'git'
        'coreutils'
        'zsh'
        'tmux'
        'the_silver_searcher'
        'wget'
        'reattach-to-user-namespace'
        'universal-ctags'
        'neovim --HEAD'
        'tree-sitter --HEAD'
    )

    # Install Homebrew (if not already installed)
    if ! command -v brew >/dev/null 2>&1; then
        echo "Homebrew not found. Installing Homebrew..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
   	(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/temp/.zprofile
    	eval "$(/opt/homebrew/bin/brew shellenv)"
    fi

    # Update Homebrew and formulae
    echo "Updating Homebrew..."
    brew update

    # Install libraries using Homebrew
    local not_found=()
    local already_installed=()
    local newly_installed=()
    for library in "${libraries[@]}"; do
        echo "Installing $library..."
        if brew list --formula | cut -d ' ' -f 1 | grep -q "^${library%% --*}\$"; then
            already_installed+=("${library%%--*}")
        elif ! brew install $library; then
            not_found+=("$library")
        else
            newly_installed+=("${library%%--*}")
        fi
    done

    if brew list --formula | cut -d ' ' -f 1 | grep -q "^fzf\$"; then
        $(brew --prefix)/opt/fzf/install
    fi

    # Display libraries not found
    if [ ${#not_found[@]} -gt 0 ]; then
        echo -e "\n\n"
        echo -e "\033[1mThe following libraries were not found:\033[0m"
        printf '\033[0;31m%s\n\033[0m' "${not_found[@]}"
        echo -e "\n\n"
    fi

    if [ ${#already_installed[@]} -gt 0 ]; then
        echo -e "\033[1mAlready installed libraries:\033[0m"
        printf '\033[0;33m%s\n\033[0m' "${already_installed[@]}"
        echo -e "\n\n"
    fi

    # List newly installed libraries from the script
    if [ ${#newly_installed[@]} -gt 0 ]; then
        echo -e "\033[1mNewly installed libraries:\033[0m"
        printf '\033[0;32m%s\n\033[0m' "${newly_installed[@]}"
        echo -e "\n\n"
    fi
}
