#!/bin/bash

run_help() {

cat <<EOT
OS X dotfiles - Cesar Gomez - http://cesargomez89.github.io/

Usage: $(basename "$0") [options]

Options:
    -h, --help      Print this help text
    -l, --list      Print a list of additional software to install
    --no-packages   Suppress package updates
    --no-sync       Suppress pulling from the remote repository

Documentation can be found at https://github.com/cesargomez89/inspiration-dotfiles/
EOT

}
