#!/bin/bash

run_neovim_install() {
	#if ! [ -d ~/.vim/ ]; then
	ruby -e "$(curl -Lo- http://bit.ly/cesar-neovim-dotfiles | bash)"
	e_success "Neovim config was successfully installed!"
	#else
	#e_header "Neovim config was already installed"
	#fi

	#e_success "#### the customizations are in .vimrc"
}
