#!/bin/bash

run_janus_vim_install() {
  if ! [ -d ~/.vim/janus/ ]; then
    ruby -e "$(curl -Lo- https://bit.ly/janus-bootstrap | bash)"
    e_success "Janus vim was successfully installed!"
  else
    e_header "Janus was already installed"
  fi

  e_success "#### the customizations are in .vimrc.before"
}
