#!/bin/bash

run_list() {

cat <<EOT

OS X dotfiles - Cesar Gomez - http://cesargomez.github.io/

Additional software to install

Browsers:
  Chrome

Development:
  docker
  git
  zsh
  tmux
  the_silver_searcher
  neovim

Other:
  Slack
  Telegram
  Spotify
EOT

}
