#!/bin/bash

run_list() {

cat <<EOT

OS X dotfiles - Cesar Gomez - http://cesargomez.github.io/

Additional software to install

Browsers:
    Firefox
    Google Chrome

Development:
    Filezilla
    VirtualBox

Gems:
    tmuxinator

Other:
    Alfred
    Divvy
    Spectacle
    Dropbox
    Skype
    uTorrent
    Flowdock
    Simplenote
EOT

}
