#!/bin/bash

run_list() {

cat <<EOT

OS X dotfiles - Cesar Gomez - http://cesargomez.github.io/

Additional software to install

Browsers:
    Firefox
    Opera

Development:
    Filezilla
    Docker

Gems:
    tmuxinator

Other:
    Tiles
    Slack
    Telegram
    Spotify
EOT

}
