#!/bin/bash

run_npm() {

  # Check for npm
  if ! type_exists 'npm'; then
    printf "\n"
    e_header "npm not found, installing..."
    ruby -e "$(curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.26.1/install.sh | bash)"
  fi

  #e_header "Installing Node.js packages..."

  # List of npm packages
  #local packages="bower grunt grunt-cli karma yo"

  # Install packages globally and quietly
  #npm install $packages --global --quiet

  [[ $? ]] && e_success "Done"

}
