#!/bin/bash

run_vim_install() {
  ruby -e "$(curl -Lo- https://bit.ly/janus-bootstrap | bash)"
  e_success "Janus vim was successfully installed!"
  if [ ! -d "~/.janus/" ]; then
    mkdir ~/.janus
  fi
  cd .janus
  local -a plugins=(
  'git@github.com:DavidEGx/ctrlp-smarttabs.git'
  'git@github.com:edkolev/tmuxline.vim.git'
  'git@github.com:jistr/vim-nerdtree-tabs.git'
  'git@github.com:christoomey/vim-tmux-navigator.git'
  'git@github.com:morhetz/gruvbox.git'
  'git@github.com:bling/vim-airline.git'
  'git@github.com:tpope/vim-surround.git'
  )

  for index in ${!plugins[*]}
  do
    git clone ${desired_formulae[$index]}
  done

  run_vimrc_list
}
