#!/bin/bash

run_vim_install() {
  if ! [ -d ~/.vim/janus/ ]; then
    ruby -e "$(curl -Lo- https://bit.ly/janus-bootstrap | bash)"
    run_vimrc_list >> ~/.vimrc
    e_success "Janus vim was successfully installed!"
  else
    e_header "Janus was already installed, installing plugins"
  fi
  mkdir -p ~/.janus
  cd ~/.janus
  local -a plugins=(
  'git@github.com:DavidEGx/ctrlp-smarttabs.git'
  'git@github.com:edkolev/tmuxline.vim.git'
  'git@github.com:jistr/vim-nerdtree-tabs.git'
  'git@github.com:christoomey/vim-tmux-navigator.git'
  'git@github.com:morhetz/gruvbox.git'
  'git@github.com:bling/vim-airline.git'
  )

  for index in ${!plugins[*]}
  do
    git clone ${plugins[$index]}
  done

  link "./lib/vimrc_before"    ".vimrc.before"

  e_success "#### the customizations are in .vimrc.before"
}
