#!/bin/bash

run_vimrc_list() {
  e_header "Add this to your .vimrc inside customizations"
cat <<EOT
let mapleader=","

if has('gui_running')
  set guifont=Droid\ Sans\ Mono\ for\ Powerline
endif

cmap w!! w !sudo tee >/dev/null %
:imap jj <Esc>

map <F5> :call ToggleBg()<CR>

let g:airline_powerline_fonts = 1
let g:pencil_higher_contrast_ui = 0   " 0=low (def), 1=high
let g:airline_theme = 'dark'

function! ToggleBg()
  if &background == 'dark'
    set bg=light
  else
    set bg=dark
  endif
endfunc

nmap <C-i> :CtrlPSmartTabs<CR>

" Align by the equal sign
 map <C-a> :Tab /=<Enter>

 " Yank to clipboard
 map <S-y> "+y

" Start of the line
map 0 ^

if exists('$TMUX')
  set term=screen-256color
endif

if exists('$ITERM_PROFILE')
  if exists('$TMUX')
    let &t_SI = "\<Esc>[3 q"
    let &t_EI = "\<Esc>[0 q"
  else
    let &t_SI = "\<Esc>]50;CursorShape=1\x7"
    let &t_EI = "\<Esc>]50;CursorShape=0\x7"
  endif
end

function! WrapForTmux(s)
  if !exists('$TMUX')
    return a:s
  endif

  let tmux_start = "\<Esc>Ptmux;"
  let tmux_end = "\<Esc>\\"

  return tmux_start . substitute(a:s, "\<Esc>", "\<Esc>\<Esc>", 'g') . tmux_end
endfunction

let &t_SI .= WrapForTmux("\<Esc>[?2004h")
let &t_EI .= WrapForTmux("\<Esc>[?2004l")

function! XTermPasteBegin()
  set pastetoggle=<Esc>[201~
  set paste
  return ""
endfunction

inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()

EOT
}
